### ISSUE TITLE
Reqwest error, expected u64

### ISSUE THREAD

**Issue by ghost** [vityafx/randomorg#7]
I am trying to run the example with my API key. But it seems like reqwest is expecting u64.

```
Result: Err(Reqwest(Error(Json(Error("invalid type: null, expected u64", line: 1, column: 90)))))
Random integers: Err(Reqwest(Error(Json(Error("invalid type: null, expected u64", line: 1, column: 90)))))
```

**Comment by iddm** [comment]
Thanks, I can confirm on the example `generate_integers`. Apparently, the serializing has changed, so picking it up.

**Comment by iddm** [comment]
Also, have added nightly-jobs to prevent this in future.

**Comment by iddm** [comment]
Going not so fast, random.org has removed my account (wow!) from their database, have spent some time on restoring it.

**Comment by iddm** [comment]
I am sorry it has taken so long. Was busy with other projects.

1. The `travis` script now runs the example every time, so this will not happen in the future.
2. [Here is the failed job](https://travis-ci.org/vityafx/randomorg/jobs/588507499) which shows the problem.
3. [Here is the solution](https://github.com/vityafx/randomorg/commit/6cc594676e3819bf50554a760adde35228f81ad2) to the problem.
4. [Here is the successful run](https://travis-ci.org/vityafx/randomorg/builds/588515871) of an example in travis.
5. [Here is the new version](https://crates.io/crates/randomorg/1.0.1) uploaded to the crates.io service.

Thank you for reporting this problem. Have a nice day.
